### ISSUE TITLE
A build for precise?

### ISSUE THREAD

**Issue by robinpaulson** [Shnatsel/cjdns-ubuntu-pubkey#1]
Hi, I used to install cjdns from your repository, then it went offline a few days ago. I wondered if there was a technical problem with the repo, or maybe now cjdns uses features only available in a newer version of the dependencies? If you could get the precise builds online, that would be great. Cheers, Robin

**Comment by Shnatsel** [comment]
Hi, Robin!

Precise is no longer supported by my repo. The official packaging now
includes a bunch of Python helper scripts to go with cjdns. This created a
build dependency on dh-python package which is not available for Precise.

However, now that I look at it, dh-python seems to be no longer used in the
packaging (as of
https://github.com/cjdelisle/cjdns/commit/57db401db8faeb9db4cb182d431a661ebddc9ce3).
I'll check if I can get rid of that dependency and enable Precise builds
again. Thanks for letting me know!

**Comment by Shnatsel** [comment]
https://github.com/cjdelisle/cjdns/pull/782 as soon as this is merged I'll
enable Precise builds again.

**Comment by Shnatsel** [comment]
Now that I'm looking at systemd integration required for 15.04, it seems
that it will conflict with 12.04 support either way.

Is there any particular reason for not upgrading to 14.04LTS on your end?

**Comment by robinpaulson** [comment]
It's a production server running a bunch of services, I don't want to mess with it unless absolutely necessary, and upgrades always cause pain. The plan was to use precise until Canonical drops support, which isn't for another 2 years. Has there been a change in cjdns which requires a dependency not available in 12.04?

**Comment by Shnatsel** [comment]
The change has been in Ubuntu itself - the migration to systemd. Because of some implementation details of Debian packaging of systemd I have to choose between supporting Ubuntu 15.04 and 12.04, I can't reasonably support both.

Since cjdns is still in alpha and may suddenly start requiring some very recent features by itself, I'll choose supporting Ubuntu 15.04 and Debian Jessie over Ubuntu 12.04.
